#!/bin/sh

#############
# Functions #
#############

# Argument $1: The name of the Homebrew package
# Argument $2: Optional custom code to run instead of Homebrew install
check_dependency () {
        command -v $1 >/dev/null 2>&1
        if [ ! $? -eq 0 ]; then
                if [ -z "$2" ]; then
                        echo "Installing $1"
                        brew update
                        brew install $1
                else
                        echo "Executing custom commands:\n"
                        eval $2
                fi
        fi
}

############
# Homebrew #
############

# Check that Homebrew is installed
# Do this manually because we need it for the check_dependency function
command -v brew >/dev/null 2>&1
if [ ! $? -eq 0 ]; then
        echo "Homebrew must be installed to run this script. Aborting."
        exit 1
fi

check_dependency "ag" "brew update && brew install the_silver_searcher"
check_dependency "git"
check_dependency "nvim"
check_dependency "python"

########################
# Neovim Configuration #
########################

NVIM_DIRECTORY=~/.config/nvim

# Make sure that the directory exists
if [ ! -d $NVIM_DIRECTORY ]; then
        mkdir -p $NVIM_DIRECTORY
fi

# Check for files / symlinks that are already there
if [ -f $NVIM_DIRECTORY/init.vim ] || [ -h $NVIM_DIRECTORY/init.vim ]; then
        rm -f $NVIM_DIRECTORY/init.vim
fi

# Symlink the config file
ln -s $PWD/Neovim/init.vim $NVIM_DIRECTORY/init.vim

# Install Pathogen
## First check if the directories for it exist
if [ ! -d $NVIM_DIRECTORY/autoload ]; then
        mkdir -p $NVIM_DIRECTORY/autoload
fi

if [ ! -d $NVIM_DIRECTORY/bundle ]; then
        mkdir -p $NVIM_DIRECTORY/bundle
fi

if [ ! -f $NVIM_DIRECTORY/autoload/pathogen.vim ]; then
        curl -LSso $NVIM_DIRECTORY/autoload/pathogen.vim https://tpo.pe/pathogen.vim
fi

# Install Pathogen Plugins
./Neovim/plugins
