#!/bin/bash

# NOTE: This script is from the manual install
# instructions in the NVM repo's README
export NVM_DIR="$HOME/dev_config/node/nvm" && (
  git clone https://github.com/creationix/nvm.git "$NVM_DIR"
  cd "$NVM_DIR"
  git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" $(git rev-list --tags --max-count=1)`
) && \. "$NVM_DIR/nvm"
