#!/bin/bash

# This is an array of plugins that we need to load.
plugins_list=()

# This file has a list of the plugins to install.
plugins_file=~/dev_config/homebrew/plugins.txt

# Load the list of plugins into an array
get_plugins_list () {
  while IFS= read -r plugin; do
    plugins_list+=("$plugin")
  done < "$plugins_file"
}

# Install/update plugins from $plugins_list
load_plugins () {
  homebrew_plugins="$(brew list)"

  for plugin in "${plugins_list[@]}"; do
    plugin_name=$( echo "$plugin" | awk '{split($0, a, "--"); gsub(/^[ \t]+/, "", a[1]); gsub(/[ \t]+$/, "", a[1]); print a[1]}' )
    plugin_script=$( echo "$plugin" | awk '{split($0, a, "--"); gsub(/^[ \t]+/, "", a[2]); gsub(/[ \t]+$/, "", a[2]); print a[2]}' )

    # If the plugin isn't installed yet install it
    if [[ ! "$homebrew_plugins" == "$plugin_name" ]]; then
      printf "Installing %s\n" "$plugin_name"
      brew install "$plugin_name"
      printf "\n"

      # If there's a post-install script run it
      if [[ ! -z "$plugin_script" ]]; then
        printf "Executing post-install script:\n"
        eval "$plugin_script"
        printf "\n"
      fi
    fi
  done
}

printf "Loading Homebrew plugins:\n\n"
brew update
get_plugins_list
load_plugins
brew upgrade
brew cleanup
brew prune
printf "Finished loading Homebrew plugins.\n\n"
