#!/bin/bash

printf "Running Homebrew plugin script.\n\n"

homebrew_plugins_file=~/dev_config/homebrew/plugins.txt # This file has a list of the plugins to install.

# Install a Homebrew package
# $1 - Name of the installed executable (The package name may be different)
# $2 - Optional custom install script
load_package () {
  # Get a list of Homebrew plugins if we don't have it yet.
  if [[ ! "$homebrew_plugins" ]]; then
    homebrew_plugins=$(brew list)
  fi

  if [[ ! "$homebrew_plugins" =~ "$1" ]]; then
    if [[ -z "$2" ]]; then
      printf "Installing %s\n" $1
      brew install "$1"
      printf "\n"
    else
      printf "Executing a custom install script:\n"
      eval $2
      printf "\n"
    fi
  fi
}

brew update
brew upgrade

for package in $(cat "$homebrew_plugins_file"); do
  load_package "$package"
done

# HACK: This needs to be done the right way.
/usr/local/opt/fzf/install

brew cleanup
brew prune

printf "Finished with Homebrew plugin script.\n\n"
