#!/bin/bash

printf "Running Homebrew plugin script.\n\n"

# The directory where our Homebrew configuration lives
homebrew_dir=~/dev_config/homebrew

# Install a Homebrew package
# $1 - Name of the installed executable (The package name may be different)
# $2 - Optional custom install script
load_package () {
  # Get a list of Homebrew packages if we don't have it yet.
  if [[ ! $homebrew_packages ]]; then
    homebrew_packages=$(brew list)
  fi

  if [[ ! "$homebrew_packages" =~ "$1" ]]; then
    if [[ -z "$2" ]]; then
      printf "Installing %s\n" $1
      brew install "$1"
      printf "\n"
    else
      printf "Executing a custom install script:\n"
      eval $2
      printf "\n"
    fi
  fi
}

brew update
brew upgrade

for package in $(cat "$homebrew_dir/packages.txt"); do
  load_package "$package"
done

brew cleanup
brew prune

printf "Finished with Homebrew plugin script.\n\n"
