#!/bin/bash

printf "Running Homebrew setup script.\n\n"

homebrew_directory=~/homebrew                                  # The installation directory for Homebrew
homebrew_url="https://github.com/Homebrew/brew/tarball/master" # The URL of the Homebrew installer script

# Is Homebrew installed already?
command -v brew >/dev/null 2>&1
if [[ ! $? -eq 0 ]]; then
  # If not we need to set it up.

  # Delete old $homebrew_directory if it's already there.
  if [[ -d "$homebrew_directory" ]]; then
    rm -rf "$homebrew_directory"
  fi

  # Install Homebrew to $homebrew_directory
  mkdir "$homebrew_directory" && curl -L "$homebrew_url" | tar xz --strip 1 -C homebrew
fi

# Install Homebrew plugins (a.k.a packages)
./homebrew/plugins

printf "Finished with Homebrew setup script.\n\n"
