#!/bin/bash

$homebrew_url = https://github.com/Homebrew/brew/tarball/master

####################
# Install Homebrew #
####################

# Is Homebrew installed already?
command -v brew >/dev/null 2>&1
if [[ ! $? -eq 0 ]]; then
        # If not we need to set it up.

        # Delete old ~/homebrew if it's already there.
        if [[ -d ~/homebrew ]]; then
                rm -rf ~/homebrew
        fi

        # Install Homebrew to ~/homebrew
        cd ~
        mkdir ~/homebrew && curl -L $homebrew_url | tar xz --strip 1 -C homebrew
fi

###################
# Update Homebrew #
###################

brew update
brew upgrade

################################
# Install Hombrew Dependencies #
################################

# TODO

##################
# Clean Homebrew #
##################

brew cleanup
brew prune
