vim.keymap.set('n', '<space>h', '<cmd>nohlsearch<CR>', { desc = 'Clear highlighted search results', noremap = true })
vim.keymap.set('n', '<space>ff', '<cmd>Telescope find_files<CR>', { noremap = true })
vim.keymap.set('n', '<space>fg', '<cmd>Telescope live_grep<CR>', { noremap = true })
vim.keymap.set('n', '<space>fb', '<cmd>Telescope buffers<CR>', { noremap = true })
vim.keymap.set('n', '<space>fh', '<cmd>Telescope help_tags<CR>', { noremap = true })
vim.keymap.set('n', '<space>t', '<cmd>NERDTreeToggle<CR>', { noremap = true })
vim.keymap.set('n', '<space>f', '<cmd>NERDTreeFind<CR>', { noremap = true })
