#!/bin/bash

gpg_deps=(gnupg gpg-agent pinentry-mac) # This software must be available for GPG to work.


# Check that Homebrew is available
command -v brew >/dev/null 2>&1 
if [[ ! $? -eq 0 ]]; then
  printf "Command brew not found.\n"
  printf "Make sure that Homebrew is installed and available on the PATH.\n"
  printf "Aborting.\n"
  exit 1
fi
