# General Config
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

# Oh-My-Zsh
export ZSH="/Users/joshuakleveter/.oh-my-zsh"
ZSH_THEME="flazz"
plugins=(fzf git gh nvm vi-mode)
source $ZSH/oh-my-zsh.sh


# Z
. /usr/local/etc/profile.d/z.sh
