# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Google Cloud SDK
if [ -f '/Users/joshuakleveter/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/joshuakleveter/google-cloud-sdk/path.zsh.inc'; fi
if [ -f '/Users/joshuakleveter/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/joshuakleveter/google-cloud-sdk/completion.zsh.inc'; fi

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

# Powerline
powerline_root=/usr/local/lib/python3.9/site-packages
. "$powerline_root"/powerline/bindings/zsh/powerline.zsh

# Z
. /usr/local/etc/profile.d/z.sh

# ZSH Syntax Highlighting
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
