#!/bin/bash

# Neovim plugins are installed here.
nvim_plugins=~/.config/nvim/bundle

# List of Neovim plugins to install.
plugins=~/dev_config/neovim/plugins.txt

# Array of the plugins that are supposed to be installed.
plugin_list=()

# Delete any plugins that are not in ./neovim/plugins.txt
clean_plugins () {
  # For each plugin that's currently installed
  for plugin in $(ls "$nvim_plugins"); do
    # Check if it's supposed to be installed
    if [[ ! "${plugin_list[@]}" =~ "$plugin" ]]; then
      # If it's not in the list delete it
      printf "Deleting plugin %s\n" "$plugin"
      rm -rf "$nvim_plugins/$plugin"
      printf "\n"
    fi
  done
}

# Load the list of plugins into an array
get_plugin_list () {
  while IFS= read -r plugin; do
    plugin_list+=("$plugin")
  done < "$plugins"
}

# Install/update plugins from $plugin_list
load_plugins () {
  for plugin in "${plugin_list[@]}"; do
    plugin_full_name=$( echo "$plugin" | awk '{split($0, a, "--"); gsub(/^[ \t]+/, "", a[1]); gsub(/[ \t]+$/, "", a[1]); print a[1]}' )
    plugin_name=$( echo "$plugin_full_name" | cut -d'/' -f2 )
    plugin_script=$( echo "$plugin" | awk '{split($0, a, "--"); gsub(/^[ \t]+/, "", a[2]); gsub(/[ \t]+$/, "", a[2]); print a[2]}' )

    # If the plugin isn't installed
    if [[ ! -d "$nvim_plugins/$plugin_name" ]]; then
      # Install it
      printf "Loading plugin %s\n" "$plugin_name"
      git clone "git://github.com/$plugin_full_name" "$nvim_plugins/$plugin_name"
      printf "\n"
    else
      # Otherwise make sure it's up to date
      printf "Updating plugin %s\n" "$plugin_name"
      cd "$nvim_plugins/$plugin_name"
      git pull
      printf "\n"
    fi

    # If there's a post-install script
    if [[ ! -z "$plugin_script" ]]; then
      # Execute it
      printf "Executing post-install script:\n"
      eval "$plugin_script"
      printf "\n"
    fi
  done
}

# Make sure that Git is available
command -v git >/dev/null 2>&1
if [[ ! "$?" -eq 0 ]]; then
  printf "Git must be installed to run this script. Aborting.\n"
  exit 1
fi

printf "Loading Neovim plugins:\n\n"
get_plugin_list
load_plugins
clean_plugins
printf "Finished loading Neovim plugins.\n\n"
