#!/bin/sh

#################
# Prerequisites #
#################

# Check if Git is installed
command -v git >/dev/null 2>&1
if [ ! $? -eq 0 ]; then
        echo "Git must be installed to run this script. Aborting."
        exit 1
fi

#############
# Functions #
#############

nvim_plugins=~/.config/nvim/bundle

# This will load a plugin from Github
# Use like this: load_plugin "mileszs/ack.vim"
load_plugin () {
        account=$( echo $1 | cut -d'/' -f1 )
        plugin=$( echo $1 | cut -d'/' -f2 )

        # If the plugin hasn't been loaded load it
        if [ ! -d $nvim_plugins/$plugin ]; then
                echo Loading: $1
                git clone git://github.com/$account/$plugin $nvim_plugins/$plugin
                echo "\n"
        else
                echo Updating: $1
                cd $nvim_plugins/$plugin
                git pull
                echo "\n"
        fi

        # Execute additional commands
        if [ ! -z "$2" ]; then
                echo "Executing custom commands"
                eval "$2"
                echo "\n"
        fi
}

#######################
# Load Neovim plugins #
#######################

echo "Loading Neovim plugins:\n"

load_plugin "mileszs/ack.vim"
load_plugin "ctrlpvim/ctrlp.vim"
load_plugin "airblade/vim-gitgutter"
load_plugin "simnalamburt/vim-mundo"
load_plugin "sheerun/vim-polyglot"
load_plugin "altercation/vim-colors-solarized"
load_plugin "vim-syntastic/syntastic"
load_plugin "valloric/youcompleteme" "cd $nvim_plugins/youcompleteme && git submodule update --init --recursive && ./install.py --js-completer"
