#!/bin/sh

#################
# Prerequisites #
#################

# Check if Git is installed
command -v git >/dev/null 2>&1
if [ ! $? -eq 0 ]; then
        echo "Git must be installed to run this script. Aborting."
        exit 1
fi

#############
# Functions #
#############

NVIM_PLUGINS=~/.config/nvim/bundle

# This will load a plugin from Github
# Use like this: load_plugin "mileszs/ack.vim"
load_plugin () {
        ACCOUNT=$( echo $1 | cut -d'/' -f1 )
        PLUGIN=$( echo $1 | cut -d'/' -f2 )

        if [ ! -d $NVIM_PLUGINS/$PLUGIN ]; then
                echo Loading: $1
                git clone git://github.com/$ACCOUNT/$PLUGIN $NVIM_PLUGINS/$PLUGIN
                echo "\n"
        fi
}

#######################
# Load Neovim plugins #
#######################

echo "Loading Neovim plugins:\n"

load_plugin "mileszs/ack.vim"
load_plugin "ctrlpvim/ctrlp.vim"
load_plugin "airblade/vim-gitgutter"
load_plugin "simnalamburt/vim-mundo"
load_plugin "sheerun/vim-polyglot"
load_plugin "altercation/vim-colors-solarized"
load_plugin "vim-syntastic/syntastic"
load_plugin "valloric/youcompleteme"
