#!/bin/bash

# This is the system directory where Neovim keeps it's configuration.
nvim_directory=~/.config/nvim

# Make sure that the directory exists
if [[ ! -d $nvim_directory ]]; then
  mkdir -p $nvim_directory
fi

# Check for files / symlinks that are already there
if [[ -f $nvim_directory/init.vim ]] || [[ -h $nvim_directory/init.vim ]]; then
  rm -f $nvim_directory/init.vim
fi

# Symlink the config file
ln -s $PWD/neovim/init.vim $nvim_directory/init.vim

# Install Pathogen
## First check if the directories for it exist
if [[ ! -d $nvim_directory/autoload ]]; then
  mkdir -p $nvim_directory/autoload
fi

if [[ ! -d $nvim_directory/bundle ]]; then
  mkdir -p $nvim_directory/bundle
fi

if [[ ! -f $nvim_directory/autoload/pathogen.vim ]]; then
  curl -LSso $nvim_directory/autoload/pathogen.vim https://tpo.pe/pathogen.vim
fi

# Install Pathogen Plugins
./neovim/plugins
