#!/bin/bash

printf "Running the Neovim setup script.\n\n"

# This is the system directory where Neovim keeps it's configuration.
nvim_directory=~/.config/nvim

# This is the URL we load Pathogen from
pathogen_url="https://tpo.pe/pathogen.vim"

# Make sure that the directory exists
if [[ ! -d "$nvim_directory" ]]; then
  mkdir -p "$nvim_directory"
fi

# Check for files / symlinks that are already there
if [[ -f "$nvim_directory/init.vim" ]] || [[ -h "$nvim_directory/init.vim" ]]; then
  rm -f "$nvim_directory/init.vim"
fi

# Symlink the config file
ln -s "$PWD/neovim/init.vim" "$nvim_directory/init.vim"

# Install Pathogen
## First check if the directories for it exist
if [[ ! -d "$nvim_directory/autoload" ]]; then
  mkdir -p "$nvim_directory/autoload"
fi

if [[ ! -d "$nvim_directory/bundle" ]]; then
  mkdir -p "$nvim_directory/bundle"
fi

if [[ ! -f "$nvim_directory/autoload/pathogen.vim" ]]; then
  curl -LSso "$nvim_directory/autoload/pathogen.vim" "$pathogen_url"
fi

# Install Pathogen Plugins
./neovim/plugins

# If Node.js / NPM is available
# install the neovim NPM package.
command -v npm >/dev/null 2>&1
if [[ "$?" -eq 0 && ! "$(npm ls -g --depth=0)" =~ "neovim" ]]; then
  printf "Installing neovim NPM package:\n"
  npm i neovim -g
fi

printf "Finished with the Neovim setup script.\n\n"
