#!/bin/sh

#################
# Prerequisites #
#################

# Check if Git is installed
command -v git >/dev/null 2>&1
if [ ! $? -eq 0 ]; then
        echo "Git must be installed to run this script. Aborting."
        exit 1
fi

######################
# Update all plugins #
######################

NVIM_PLUGINS=~/.config/nvim/bundle

echo "Updating Neovim plugins.\n"

for plugin in $( ls $NVIM_PLUGINS ); do
        echo Updating $plugin
        cd $NVIM_PLUGINS/$plugin
        git pull
        echo "\n"
done

echo "Done updating Neovim plugins."
